name: deploy

on:
  push:
    branches: [main]

env:
  SERVER_CWD: ~/projects/jeremiaaxel.github.io/

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Check SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SECRET_KEY }}
          script: |
            echo "SSH OK"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11

      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun run build

      - name: Zip artifact for deployment
        run: zip -rq release.zip ./* .svelte-kit

      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SECRET_KEY }}
          source: release.zip
          target: ${{ env.SERVER_CWD }}

      - name: Unzip Artifacts and Remove Zip
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SECRET_KEY }}
          script: |
            cd ${{ env.SERVER_CWD }}
            unzip -oq release.zip
            rm release.zip

      - name: Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SECRET_KEY }}
          script: |
            cd ${{ env.SERVER_CWD }}
            export PATH=$PATH:~/.bun/bin
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pm2 startOrRestart ecosystem.config.cjs
