name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Check SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          echo "SSH OK"

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.11

    - name: Install dependencies
      run:
        bun install

    - name: Build the project
      run:
        bun run build

    - name: Copy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SERVER_KEY }}
        source: "build,.svelte-kit,node_modules,bun.lockb,package.json"
        target: "/projects/jeremiaaxel.github.io/"

    - name: Restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          pm2 restart ${{ secrets.PM2_NAME }}
